version: "3.9"

services:
  database:
    image: postgres
    container_name: ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
